RegisterNUICallback('get-bank', function(_, cb)
    lib.callback('z-phone:server:GetBank', false, function(bank)
        cb(bank)
    end)
end)

RegisterNUICallback('pay-invoice', function(body, cb)
    lib.callback('z-phone:server:PayInvoice', false, function(isOk)
        cb(isOk)
    end, body)
end)

RegisterNUICallback('transfer-check', function(body, cb)
    lib.callback('z-phone:server:TransferCheck', false, function(result)
        cb(result)
    end, body)
end)

RegisterNUICallback('transfer', function(body, cb)
    lib.callback('z-phone:server:Transfer', false, function(isOk)
        cb(isOk)
    end, body)
end)