RegisterNUICallback('get-bank', function(_, cb)
    lib.callback('z-phone:server:GetBank', false, function(bank)
        cb(bank)
    end)
end)

RegisterNUICallback('pay-invoice', function(body, cb)
    lib.callback('z-phone:server:PayInvoice', false, function(isOk)
        cb(isOk)
    end, body)
end)