RegisterNUICallback('new-or-continue-chat', function(body, cb)
    lib.callback('z-phone:server:StartOrContinueChatting', false, function(chatting)
        cb(chatting)
    end, body)
end)

RegisterNUICallback('get-chats', function(_, cb)
    lib.callback('z-phone:server:GetChats', false, function(chats)
        cb(chats)
    end)
end)

RegisterNUICallback('get-chatting', function(body, cb)
    lib.callback('z-phone:server:GetChatting', false, function(chatting)
        cb(chatting)
    end, body)
end)

RegisterNUICallback('send-chatting', function(body, cb)
    lib.callback('z-phone:server:SendChatting', false, function(isOk)
        cb(isOk)
    end, body)
end)