RegisterNUICallback('get-contacts', function(_, cb)
    lib.callback('z-phone:server:GetContacts', false, function(contacts)
        cb(contacts)
    end)
end)

RegisterNUICallback('delete-contact', function(body, cb)
    lib.callback('z-phone:server:DeleteContact', false, function(isOk)
        cb(isOk)
    end, body)
end)

RegisterNUICallback('update-contact', function(body, cb)
    lib.callback('z-phone:server:UpdateContact', false, function(isOk)
        cb(isOk)
    end, body)
end)